version: "3.3"
services:
    php:
      image: greg0/php-runtime-env:php7.4-dev
      volumes:
        # Dev
        - ../src:/var/www
        - ../images/php-config/php.ini:/usr/local/etc/php/conf.d/docker-php-project.ini
        - ../images/php-config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug2.ini
