version: "3.3"
services:

    memcached:
      image: memcached:alpine

    mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine

    mariadb:
      image: mariadb:latest
      working_dir: /var/www
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "8083:3306"

    webserver:
      image: greg0-nginx
      working_dir: /var/www
      restart: always
      depends_on:
        - php
      logging:
        driver: "json-file"
        options:
          max-size: "500k"
          max-file: "50"
      volumes:
          - ../src:/var/www
          - ../tmp/logs/nginx:/var/log/nginx
      ports:
       - "8080:80"

    php:
      image: greg0-php
      working_dir: /var/www
      depends_on:
        - mariadb
        - redis
        - mailhog
        - memcached
      volumes:
        # Dev
        - ../src:/var/www
        - ../images/php/php.ini:/usr/local/etc/php/conf.d/docker-php-project.ini
